### ISSUE TITLE
Would it be better to refactor"forward/back_propagate" as trait method for `Layer`?

### ISSUE THREAD

**Issue by dbsxdbsx** [goldstraw/rust_cnn#1]
Just glad to see such an ML repo written in rust.   Just come up with a thought: 
 maybe refactoring "forward/back_propagate" as a trait method for `Layer` is a good way to organize the layer code.

**Comment by goldstraw** [comment]
You're correct, it's much more logical to implement the forward / backpropagation in this way. I've implemented this suggestion, thank you!
